### ISSUE TITLE
Key Error on GUILD_UPDATE

### ISSUE THREAD

**Issue by Th3-M4jor** [Kraigie/nostrum#290]
This is another case of Discord being inconsistent in using strings or atoms as keys when using ETF payloads.

If this happens more than once in a quick enough succession, the cache process is not restarted and events stop being sent to the user's Consumer process.

This currently happens on the latest commit to `master`.

```
[error] GenServer Nostrum.Shard.Stage.Cache terminating
** (KeyError) key :id not found in: %{"id" => [guild_id], "verification_level" => 1, "preferred_locale" => "en-US", "afk_channel_id" => nil, "vanity_url_code" => nil, [ . . . ]}
```

Stacktrace:
```
(nostrum 0.4.7) lib/nostrum/cache/guild_cache.ex:204: Nostrum.Cache.GuildCache.update/1
(nostrum 0.4.7) lib/nostrum/shard/dispatch.ex:151: Nostrum.Shard.Dispatch.handle_event/3
(nostrum 0.4.7) lib/nostrum/shard/dispatch.ex:42: Nostrum.Shard.Dispatch.handle/1
(elixir 1.12.0) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
(nostrum 0.4.7) lib/nostrum/shard/stage/cache.ex:23: Nostrum.Shard.Stage.Cache.handle_events/3
(gen_stage 1.1.0) lib/gen_stage.ex:2462: GenStage.consumer_dispatch/6
(gen_stage 1.1.0) lib/gen_stage.ex:2641: GenStage.take_pc_events/3
(stdlib 3.15.2) gen_server.erl:695: :gen_server.try_dispatch/4
```

**Comment by jchristgit** [comment]
99 little inconsistencies in the ETF gateway,
99 little inconsistencies in the ETF gateway,
Take one down, patch it around
117 little inconsistencies in the ETF gateway
