### ISSUE TITLE
Unable to reproduce AudioPlayer example from docs

### ISSUE THREAD

**Issue by on3dd** [Kraigie/nostrum#337]
Trying to reproduce the example with voice channels from the documentation, but after starting the audio playback, the bot immediately stops speaking.

Logs: 
```
17:39:47.649 [debug] VOICE SPEAKING UPDATE %Nostrum.Struct.Event.SpeakingUpdate{channel_id: 580931507712032792, guild_id: 580931507288539177, speaking: true}

17:39:51.591 [debug] VOICE SPEAKING UPDATE %Nostrum.Struct.Event.SpeakingUpdate{channel_id: 580931507712032792, guild_id: 580931507288539177, speaking: false}
```

Source code: https://github.com/on3dd/berezovskiy

What could be the problem? Thank you in advance.

**Comment by on3dd** [comment]
Sorry for late response, I tried your suggestion, but it didn't solve the problem.
With the following code:
```elixir
defmodule Berezovskiy.Consumer.MessageCreate do
  ...

  @local_mp3_url "~/code/berezovskiy/Kalimba.mp3"

  ...

  def handle(msg) do
    ...

    "!play song" ->
        if Voice.ready?(msg.guild_id) do
          Voice.play(msg.guild_id, @local_mp3_url, :url)
        else
          do_not_ready_msg(msg)
        end

    ...
  end
end
```
I still get the following logs:
```
20:21:50.510 [debug] VOICE SPEAKING UPDATE %Nostrum.Struct.Event.SpeakingUpdate{channel_id: 580931507712032792, guild_id: 580931507288539177, speaking: true}
 
20:21:50.718 [debug] VOICE SPEAKING UPDATE %Nostrum.Struct.Event.SpeakingUpdate{channel_id: 580931507712032792, guild_id: 580931507288539177, speaking: false}
```
and the bot still doesn't speak 😞

**Comment by tionis** [comment]
Can confirm, I had the same or a similar issue but using the master branch and realtime: false fixed it for me.

**Comment by chanphiromsok** [comment]
I had this issued too After play music from youtube it sound about 2sec then speaking turn to false

**Comment by jchristgit** [comment]
I'm closing this for now pending response, feel free to re-open if you're still encountering the issue with `realtime: false` on the most recent Nostrum version `0.5.0-rc2`.

**Comment by sylvester-roos** [comment]
I'd like to re-open this issue because I'm having the same issue. I make my bot join my voice channel with `/summon`, and then I use `/play song` to play the soundcloud url, but it prints in chat that it has to be in a voice channel before being able to play audio. This happens with both the normal `Voice.play` and when I've added `realtime: false` as an option:
`[%{name: "song"}] -> Voice.play(guild_id, @soundcloud_url, :ytdl, realtime: false)`

**Comment by BrandtHill** [comment]
This will occur when your bot joins a voice channel without `guild_voice_states` gateway intents enabled.
https://kraigie.github.io/nostrum/gateway_intents.html

**Comment by sylvester-roos** [comment]
Well, I'm not sure what is going on, but it's not working for me. Can you confirm that the following code should work?
[audio_player_bot.zip](https://github.com/Kraigie/nostrum/files/14417583/audio_player_bot.zip)

In this project I run `iex -S mix`, `AudioPlayerSupervisor.start_link([])`, and `AudioPlayerConsumer.create_guild_commands(12345) # guild id here`. Then I have the bot join with `/summon` and I test it with `/play song`, after which it says in chat that it needs to be in a voice channel.

I noticed that I'm getting the following errors in the terminal. I'm assuming it's related.

<details>
<summary>logs</summary

```
10:41:30.277 [error] GenServer #PID<0.326.0> terminating
** (FunctionClauseError) no function clause matching in Nostrum.Voice.Session.terminate/2
    (nostrum 0.8.0) lib/nostrum/voice/session.ex:205: Nostrum.Voice.Session.terminate({%Nostrum.Error.CacheError{message: "ERROR: No match for 1168655087745380406 found in Elixir.Nostrum.Cache.ChannelCache"}, [{Nostrum.Util, :bangify_find, 3, [file: ~c"lib/nostrum/util.ex", line: 100]}, {Nostrum.Voice.Session, :handle_continue, 2, [file: ~c"lib/nostrum/voice/session.ex", line: 33]}, {:gen_server, :try_handle_continue, 3, [file: ~c"gen_server.erl", line: 1085]}, {:gen_server, :loop, 7, [file: ~c"gen_server.erl", line: 995]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 241]}]}, nil)
    (stdlib 5.2) gen_server.erl:1143: :gen_server.try_terminate/3
    (stdlib 5.2) gen_server.erl:1339: :gen_server.terminate/10
    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:continue, %Nostrum.Struct.VoiceState{guild_id: 1168655086751338506, channel_id: 1168655087745380406, self_mute: false, self_deaf: false, gateway: "rotterdam3894.discord.media:443", session: "3a71e626bcc59c4853cf4d87df71ac83", token: "965e0b054e038e9d", secret_key: nil, session_pid: nil, ssrc: nil, speaking: nil, ip: nil, port: nil, udp_socket: nil, rtp_sequence: nil, rtp_timestamp: nil, ffmpeg_proc: nil, raw_audio: nil, raw_stateful: nil, current_url: nil, player_pid: nil, persist_source: nil, persist_playback: nil}}
State: nil

10:41:30.278 [error] GenServer #PID<0.328.0> terminating
** (FunctionClauseError) no function clause matching in Nostrum.Voice.Session.terminate/2
    (nostrum 0.8.0) lib/nostrum/voice/session.ex:205: Nostrum.Voice.Session.terminate({%Nostrum.Error.CacheError{message: "ERROR: No match for 1168655087745380406 found in Elixir.Nostrum.Cache.ChannelCache"}, [{Nostrum.Util, :bangify_find, 3, [file: ~c"lib/nostrum/util.ex", line: 100]}, {Nostrum.Voice.Session, :handle_continue, 2, [file: ~c"lib/nostrum/voice/session.ex", line: 33]}, {:gen_server, :try_handle_continue, 3, [file: ~c"gen_server.erl", line: 1085]}, {:gen_server, :loop, 7, [file: ~c"gen_server.erl", line: 995]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 241]}]}, nil)
    (stdlib 5.2) gen_server.erl:1143: :gen_server.try_terminate/3
    (stdlib 5.2) gen_server.erl:1339: :gen_server.terminate/10
    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:continue, %Nostrum.Struct.VoiceState{guild_id: 1168655086751338506, channel_id: 1168655087745380406, self_mute: false, self_deaf: false, gateway: "rotterdam3894.discord.media:443", session: "3a71e626bcc59c4853cf4d87df71ac83", token: "965e0b054e038e9d", secret_key: nil, session_pid: nil, ssrc: nil, speaking: nil, ip: nil, port: nil, udp_socket: nil, rtp_sequence: nil, rtp_timestamp: nil, ffmpeg_proc: nil, raw_audio: nil, raw_stateful: nil, current_url: nil, player_pid: nil, persist_source: nil, persist_playback: nil}}
State: nil

10:41:30.278 [error] GenServer #PID<0.329.0> terminating
** (FunctionClauseError) no function clause matching in Nostrum.Voice.Session.terminate/2
    (nostrum 0.8.0) lib/nostrum/voice/session.ex:205: Nostrum.Voice.Session.terminate({%Nostrum.Error.CacheError{message: "ERROR: No match for 1168655087745380406 found in Elixir.Nostrum.Cache.ChannelCache"}, [{Nostrum.Util, :bangify_find, 3, [file: ~c"lib/nostrum/util.ex", line: 100]}, {Nostrum.Voice.Session, :handle_continue, 2, [file: ~c"lib/nostrum/voice/session.ex", line: 33]}, {:gen_server, :try_handle_continue, 3, [file: ~c"gen_server.erl", line: 1085]}, {:gen_server, :loop, 7, [file: ~c"gen_server.erl", line: 995]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 241]}]}, nil)
    (stdlib 5.2) gen_server.erl:1143: :gen_server.try_terminate/3
    (stdlib 5.2) gen_server.erl:1339: :gen_server.terminate/10
    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:continue, %Nostrum.Struct.VoiceState{guild_id: 1168655086751338506, channel_id: 1168655087745380406, self_mute: false, self_deaf: false, gateway: "rotterdam3894.discord.media:443", session: "3a71e626bcc59c4853cf4d87df71ac83", token: "965e0b054e038e9d", secret_key: nil, session_pid: nil, ssrc: nil, speaking: nil, ip: nil, port: nil, udp_socket: nil, rtp_sequence: nil, rtp_timestamp: nil, ffmpeg_proc: nil, raw_audio: nil, raw_stateful: nil, current_url: nil, player_pid: nil, persist_source: nil, persist_playback: nil}}
State: nil

10:41:30.278 [error] GenServer #PID<0.330.0> terminating
** (FunctionClauseError) no function clause matching in Nostrum.Voice.Session.terminate/2
    (nostrum 0.8.0) lib/nostrum/voice/session.ex:205: Nostrum.Voice.Session.terminate({%Nostrum.Error.CacheError{message: "ERROR: No match for 1168655087745380406 found in Elixir.Nostrum.Cache.ChannelCache"}, [{Nostrum.Util, :bangify_find, 3, [file: ~c"lib/nostrum/util.ex", line: 100]}, {Nostrum.Voice.Session, :handle_continue, 2, [file: ~c"lib/nostrum/voice/session.ex", line: 33]}, {:gen_server, :try_handle_continue, 3, [file: ~c"gen_server.erl", line: 1085]}, {:gen_server, :loop, 7, [file: ~c"gen_server.erl", line: 995]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 241]}]}, nil)
    (stdlib 5.2) gen_server.erl:1143: :gen_server.try_terminate/3
    (stdlib 5.2) gen_server.erl:1339: :gen_server.terminate/10
    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:continue, %Nostrum.Struct.VoiceState{guild_id: 1168655086751338506, channel_id: 1168655087745380406, self_mute: false, self_deaf: false, gateway: "rotterdam3894.discord.media:443", session: "3a71e626bcc59c4853cf4d87df71ac83", token: "965e0b054e038e9d", secret_key: nil, session_pid: nil, ssrc: nil, speaking: nil, ip: nil, port: nil, udp_socket: nil, rtp_sequence: nil, rtp_timestamp: nil, ffmpeg_proc: nil, raw_audio: nil, raw_stateful: nil, current_url: nil, player_pid: nil, persist_source: nil, persist_playback: nil}}
State: nil
```

</details>

**Comment by sylvester-roos** [comment]
Ok, it's working now! Thanks for your time
