### ISSUE TITLE
Repeated shard process crashing when embedded game is active

### ISSUE THREAD

**Issue by Bentheburrito** [Kraigie/nostrum#351]
Hi all, as requested in the Discord API server I'm posting an issue here.

I'm getting a `(Protocol.UndefinedError) protocol Enumerable not implemented for %{__struct__: Shared.EmbeddedActivity ... }` error when people are playing the new voice chat games. Nostrum tries to reconnect a few seconds later but just crashes immediately, and this repeats in a loop. This is on the hex release, 0.4.

Here's the error:
```elixir
 00:51:26.239 [error] GenServer #PID<0.1565.0> terminating
 ** (Protocol.UndefinedError) protocol Enumerable not implemented for %{__struct__: Shared.EmbeddedActivity, application_id: 755827207812677713, assets: %{"large_image" => "839608726894018561", "large_text" => "Poker Night", "small_text" => "Poker Night"}, created_at: nil, details: nil, name: "Poker Night", secrets: %{"join" => "92axxxxxx"}, state: "Playing Poker", timestamps: nil, type: 0} of type Shared.EmbeddedActivity (a struct). This protocol is implemented for the following type(s): Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.Stream, DBConnection.PrepareStream, List, HashDict, Map, HashSet, GenEvent.Stream, IO.Stream, Function, Date.Range, MapSet, Stream, File.Stream, Range
     (elixir 1.10.4) lib/enum.ex:1: Enumerable.impl_for!/1
     (elixir 1.10.4) lib/enum.ex:141: Enumerable.reduce/3
     (elixir 1.10.4) lib/enum.ex:3383: Enum.reduce/3
     (nostrum 0.4.6) lib/nostrum/util.ex:177: Nostrum.Util.safe_atom_map/1
     (nostrum 0.4.6) lib/nostrum/util.ex:177: anonymous fn/2 in Nostrum.Util.safe_atom_map/1
     (stdlib 3.13) maps.erl:233: :maps.fold_1/3
     (nostrum 0.4.6) lib/nostrum/util.ex:177: Nostrum.Util.safe_atom_map/1
     (elixir 1.10.4) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
```
There's also printouts like these with every crash but I'm not sure if they're very helpful
```elixir
Last message: {:gun_ws, #PID<0.1582.0>, #Reference<0.1808289973.894435329.231982>, {:binary, <<236, 61, 11, 112, 27, 229, 153, 191, 21, 91, 118, 100, 39, 118, 18, 59, 78, 12, 137, 23, 66, 18, 39, 84, 169, 118, 87, 79, 31, 80, 91, 182, 28, 59, 216, 142, 176, 157, 228, 146, 41, 40, 43, 105, ...>>}}
State: %Nostrum.Struct.WSState{conn: #PID<0.1582.0>, conn_pid: #PID<0.1565.0>, gateway: "gateway.discord.gg/?compress=zlib-stream&encoding=etf&v=6", heartbeat_ack: true, heartbeat_interval: 41250, heartbeat_ref: {-576460687099438, #Reference<0.1808289973.894435329.231994>}, last_heartbeat_ack: ~U[2021-11-03 00:51:26.139796Z], last_heartbeat_send: ~U[2021-11-03 00:51:26.103404Z], seq: 2, session: "7a8323c7de421ecd5b1e91bef2b8a5ac", shard_num: 0, shard_pid: nil, zlib_ctx: #Reference<0.1808289973.894566401.231988>}

00:51:26.240 [info]  WAITING 5273 BEFORE NEXT SHARD CONNECT
```

Let me know if I can provide any more info!

**Comment by jchristgit** [comment]
@jb3 do you have time to check this issue?

**Comment by portasynthinca3** [comment]
Experiencing the same issue

**Comment by jb3** [comment]
Relaying come comments from Discord:
- It's believed that this is fixed in Nostrum master? Although we haven't cut a release yet so this isn't on Hex.
- `Shared.EmbeddedActivity` doesn't seem to come from us, it's something Discord have accidentally left in while serialising to ETF and sending over the gateway. We should report this upstream if we can confirm that's happening, it's a funny bug.

**Comment by portasynthinca3** [comment]
> It's believed that this is fixed in Nostrum master? Although we haven't cut a release yet so this isn't on Hex.

Doesn't seem like it:
`mix.exs`:
```elixir
  defp deps do
    [
      {:nostrum, github: "kraigie/nostrum", ref: "master"},
    ]
  end
```
still outputs (potentially sensitive data left out):
```
20:09:53.427 [info]  ready
 
20:09:53.779 shard=0 [error] GenServer #PID<0.317.0> terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for %{__struct__: Shared.EmbeddedActivity, application_id: <...>, assets: %{"large_image" => "<...>"}, created_at: nil, details: "<...>", name: "<...>", secrets: %{"join" => "<...>"}, state: "<...>", timestamps: nil, type: 3} of type Shared.EmbeddedActivity (a struct). This protocol is implemented for the following type(s): Timex.Interval, File.Stream, Date.Range, MapSet, Function, Map, IO.Stream, HashSet, Range, List, GenEvent.Stream, Stream, HashDict                                                                                                                        
    (elixir 1.12.3) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.12.3) lib/enum.ex:141: Enumerable.reduce/3
    (elixir 1.12.3) lib/enum.ex:3958: Enum.reduce/3
    (nostrum 0.5.0) lib/nostrum/util.ex:132: Nostrum.Util.safe_atom_map/1
    (nostrum 0.5.0) lib/nostrum/util.ex:132: anonymous fn/2 in Nostrum.Util.safe_atom_map/1
    (stdlib 3.15.2) maps.erl:410: :maps.fold_1/3
    (nostrum 0.5.0) lib/nostrum/util.ex:132: Nostrum.Util.safe_atom_map/1
    (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
Last message: {:gun_ws, #PID<0.319.0>, #Reference<0.2947459763.1094451202.38231>, {:binary, <<236, 93, 91, 104, 28, 85, 24, 158, 52, 137, 73, 55, 105, 155, 212, 182, 120, 129, 116, 172, 66, 11, 165, 233, 92, 206, 220, 182, 86, 186, 185, 41, 180, 73, 107, 18, 104, 235, 45, 61, 51, 115, 38, 217, ...>>}}                                                                                              
State: %Nostrum.Struct.WSState{conn: #PID<0.319.0>, conn_pid: #PID<0.317.0>, gateway: "gateway.discord.gg/?compress=zlib-stream&encoding=etf&v=8", heartbeat_ack: true, heartbeat_interval: 41250, heartbeat_ref: {-576460708941489, #Reference<0.2947459763.1094451202.38556>}, last_heartbeat_ack: ~U[2021-12-02 19:09:52.423300Z], last_heartbeat_send: ~U[2021-12-02 19:09:52.286855Z], seq: 208, session: "<...>", shard_num: 0, shard_pid: nil, stream: #Reference<0.2947459763.1094451202.38231>, zlib_ctx: #Reference<0.2947459763.1094582274.38458>}                          
 
20:09:53.915 [info]  WAITING 3581 BEFORE NEXT SHARD CONNECT
```

**Comment by jb3** [comment]
Fixed upstream by Discord in discord/discord-api-docs#4196.

**Comment by jb3** [comment]
Thanks!
