### ISSUE TITLE
Release 0.6 in hex

### ISSUE THREAD

**Issue by frm** [Kraigie/nostrum#423]
`0.6` isn't released on hex.pm (even though the README points to a `0.6` version) and the current `master` branch includes important fixes (#418 is a pretty important change for new bot tokens).

Probably the best is to release `0.6` or at least a `0.5.2`

**Comment by jchristgit** [comment]
0.6.0 was released yesterday.

**Comment by gor181** [comment]
Hi team,

Apologies for resurrecting the old thread, however, in `0.6.0` the same issue with tokens is present?

```
warning: the following fields are unknown when raising RuntimeError: [exception: %FunctionClauseError{args: nil, arity: 3, clauses: nil, function: :decode_list_to_string, kind: nil, module: :base64}]. Please make sure to only give known fields when raising or redefine RuntimeError.exception/1 to discard unknown fields. Future Elixir versions will raise on unknown fields given to raise/2
  (elixir 1.13.4) lib/exception.ex:722: RuntimeError.exception/1
  (nostrum 0.6.0) lib/nostrum/token.ex:59: Nostrum.Token.decode_user_id!/1
  (nostrum 0.6.0) lib/nostrum/application.ex:12: Nostrum.Application.start/2
  (kernel 8.4.1) application_master.erl:293: :application_master.start_it_old/4

10:13:54.763 mfa=:application_controller.info_exited/3 [notice] Application nostrum exited: exited in: Nostrum.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (RuntimeError) Invalid token format. Copy it again from the "Bot" tab of your Application in the Discord Developer Portal.
            (stdlib 4.0.1) base64.erl:410: :base64.decode_list_to_string([], 12, 0)
            (stdlib 4.0.1) base64.erl:429: :base64.decode_list_to_string/4
            (nostrum 0.6.0) lib/nostrum/token.ex:53: Nostrum.Token.decode_user_id!/1
            (nostrum 0.6.0) lib/nostrum/application.ex:12: Nostrum.Application.start/2
            (kernel 8.4.1) application_master.erl:293: :application_master.start_it_old/4
10:13:54.771 mfa=:application_controller.info_exited/3 [notice] Application gen_stage exited: :stopped
10:13:54.771 mfa=:application_controller.info_exited/3 [notice] Application mime exited: :stopped
10:13:54.771 mfa=:application_controller.info_exited/3 [notice] Application kcl exited: :stopped
10:13:54.771 mfa=:application_controller.info_exited/3 [notice] Application poly1305 exited: :stopped
10:13:54.771 mfa=:application_controller.info_exited/3 [notice] Application equivalex exited: :stopped
10:13:54.771 mfa=:application_controller.info_exited/3 [notice] Application chacha20 exited: :stopped
10:13:54.772 mfa=:application_controller.info_exited/3 [notice] Application salsa20 exited: :stopped
10:13:54.772 mfa=:application_controller.info_exited/3 [notice] Application curve25519 exited: :stopped
10:13:54.772 mfa=:application_controller.info_exited/3 [notice] Application ed25519 exited: :stopped
10:13:54.772 mfa=:application_controller.info_exited/3 [notice] Application certifi exited: :stopped
10:13:54.773 mfa=:application_controller.info_exited/3 [notice] Application gun exited: :stopped
10:13:54.773 mfa=:application_controller.info_exited/3 [notice] Application cowlib exited: :stopped
10:13:54.773 mfa=:application_controller.info_exited/3 [notice] Application jason exited: :stopped
** (Mix) Could not start application nostrum: exited in: Nostrum.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (RuntimeError) Invalid token format. Copy it again from the "Bot" tab of your Application in the Discord Developer Portal.
            (stdlib 4.0.1) base64.erl:410: :base64.decode_list_to_string([], 12, 0)
            (stdlib 4.0.1) base64.erl:429: :base64.decode_list_to_string/4
            (nostrum 0.6.0) lib/nostrum/token.ex:53: Nostrum.Token.decode_user_id!/1
            (nostrum 0.6.0) lib/nostrum/application.ex:12: Nostrum.Application.start/2
            (kernel 8.4.1) application_master.erl:293: :application_master.start_it_old/4
```

Token: `MTAwMzIxMjcyNDAyMjU1ODc4MA.GHTNKH.5sazA-suCzT731yIVyk8gcwlVqYf7MpeqzkyBc`
**Note: I have invalidated it.**

Setting the package target to Github resolves the issue:

```
iex(1)> 10:16:32.132 mfa=Nostrum.Shard.Session.handle_continue/2 [debug] Websocket connection up on worker #PID<0.1703.0>
10:16:32.136 mfa=Nostrum.Shard.Event.handle/3 [info] IDENTIFYING
10:16:32.327 mfa=Nostrum.Shard.Event.handle/3 [debug] HEARTBEAT_ACK
```

I could be doing something wrong but I'm doubting that 😄 
Do note I'm running:

```
erlang 25.0.3
elixir 1.13.4-otp-25
```

**Comment by gor181** [comment]
Ok seems sorted with https://github.com/Kraigie/nostrum/pull/429.

**Comment by tjb** [comment]
@gor181 I am getting this error as well with 0.6.0. Any work around or should we just use the master branch for now?

**Comment by jchristgit** [comment]
I will release 0.6.1 this evening to have a hex release with the patch in it.

**Comment by gor181** [comment]
I used master for now. Release should be few days away if I understood
correctly.
